### PR TITLE
[ci] Upload build asset data to darc/maestro

### PR DESCRIPTION
**Pull request by pjcollins**
Context: https://github.com/xamarin/xamarin-android/pull/5808

The `nuget_signing` stage has been updated to publish information about
Microsoft.Maui.Graphics .nupkg files to the dotnet Maestro server.

With this data being published, the `darc` tool can now be used to
manage a Microsoft.Maui.Graphics product dependency:

    darc add-dependency -n Microsoft.Maui.Graphics -t product -r https://github.com/dotnet/Microsoft.Maui.Graphics -v 1.2.3

For dependency updating to work, we must configure "default channel"
associations for all Microsoft.Maui.Graphics branches that other repos
may be interested in tracking.  The `darc` tool can be used to do this
manually:

    darc add-default-channel --channel ".NET 6 MAUI" --branch "main" --repo https://github.com/dotnet/Microsoft.Maui.Graphics

This default channel configuration ensures that all new builds produced
by the main branch will be associated with the ".NET 6 MAUI" channel.
Microsoft.Maui.Graphics consumers can then update to the latest build
available from main with the `update-dependencies` command:

    darc update-dependencies --channel ".NET 6 MAUI"

### CODE REVIEW

**Comment by pjcollins** [comment]
Looks like this is working:

```
$ darc get-build --id 130618
Repository:    https://github.com/dotnet/Microsoft.Maui.Graphics
Branch:        push-maestro
Commit:        2abebcf1cdbe89f8a14722d232d5f181a3a90c7c
Build Number:  6.0.300-rc.2.1177+sha.2abebcf-azdo.5936113
Date Produced: 3/25/2022 3:00 PM
Build Link:    https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=5936113
BAR Build Id:  130618
Released:      False
Channels:
```

**Comment by rmarinho** [comment]
Should the channels be the same we have for the other sdks ?

**Comment by pjcollins** [comment]
Yeah I think it would make sense to use the same default channel settings as android and macios.

**Comment by rmarinho** [comment]
https://github.com/xamarin/xamarin-android (.NET 6.0.3xx SDK) ==> 'https://github.com/dotnet/maui' ('main')

**Review by rmarinho — APPROVED** [review]

**Pull request merged**
