### PR TITLE
Initial Pass at service removal / rename

### PR DESCRIPTION
**Pull request by Redth**
Lots of changes...

 - Remove Services, no more singletons
 - Make more things internal (for now)
 - Rename native -> platform

### CODE REVIEW

**Review by mattleibow — COMMENTED** [review]
Looking at the code I think it is making more sense, but one thing that I see is the use of MemoryImage. Tjhse images can't be drawn because each of the platform canvas implementations first do a check of `if (image is <platform>Image)`. Maybe they should be converted to it first?

**Comment by Redth** [comment]
Other things to fix:

- ILoggingService - remove and throw instead
- CanvasDefaults
- ConsoleLoggingSErvice
- InvariantExtensions
- Logger
- LogType
- NumericExtensions
- XmlnsPrefixAttribute - can this be internal?
- PlatformImage - throw PlatformNotSupported instead of logging
- Immutable vs Mutable namespaces - do we need subnamespaces

**Review by jsuarezruiz — COMMENTED** [review]
Not related directly with the PR, but there are some details:
- There are quite a few warnings of unused variables, etc. In another PR we could refactor a bit and clean up.

```
11>C:\Projects\Microsoft.Maui.Graphics\src\Microsoft.Maui.Graphics.Skia\SkiaCanvasState.cs(330,16,330,22): warning CS0108: 'SkiaCanvasState.ScaleX' hides inherited member 'CanvasState.ScaleX'. Use the new keyword if hiding was intended.
11>C:\Projects\Microsoft.Maui.Graphics\src\Microsoft.Maui.Graphics.Skia\SkiaCanvasState.cs(332,16,332,22): warning CS0108: 'SkiaCanvasState.ScaleY' hides inherited member 'CanvasState.ScaleY'. Use the new keyword if hiding was intended.
11>C:\Projects\Microsoft.Maui.Graphics\src\Microsoft.Maui.Graphics.Skia\SkiaCanvasState.cs(360,78,360,111): warning CS0618: 'SKDropShadowImageFilterShadowMode' is obsolete: 'Use CreateDropShadow or CreateDropShadowOnly instead.'
11>C:\Projects\Microsoft.Maui.Graphics\src\Microsoft.Maui.Graphics.Skia\SkiaCanvasState.cs(360,20,360,136): warning CS0618: 'SKImageFilter.CreateDropShadow(float, float, float, float, SKColor, SKDropShadowImageFilterShadowMode, SKImageFilter, SKImageFilter.CropRect)' is obsolete: 'Use CreateDropShadow or CreateDropShadowOnly instead.'
11>C:\Projects\Microsoft.Maui.Graphics\src\Microsoft.Maui.Graphics.Skia\SkiaCanvas.cs(11,29,11,42): warning CS0414: The field 'SkiaCanvas._shaderMatrix' is assigned but its value is never used
```

- What will happen with platforms not supported in .NET MAUI (WPF etc)? Separate into Core/Community libraries or similar?

**Review by jsuarezruiz — DISMISSED** [review]

**Comment by jsuarezruiz** [comment]
> Not related directly with the PR, but there are some details:
> 
> * There are quite a few warnings of unused variables, etc. In another PR we could refactor a bit and clean up.
> 
> ```
> 11>C:\Projects\Microsoft.Maui.Graphics\src\Microsoft.Maui.Graphics.Skia\SkiaCanvasState.cs(330,16,330,22): warning CS0108: 'SkiaCanvasState.ScaleX' hides inherited member 'CanvasState.ScaleX'. Use the new keyword if hiding was intended.
> 11>C:\Projects\Microsoft.Maui.Graphics\src\Microsoft.Maui.Graphics.Skia\SkiaCanvasState.cs(332,16,332,22): warning CS0108: 'SkiaCanvasState.ScaleY' hides inherited member 'CanvasState.ScaleY'. Use the new keyword if hiding was intended.
> 11>C:\Projects\Microsoft.Maui.Graphics\src\Microsoft.Maui.Graphics.Skia\SkiaCanvasState.cs(360,78,360,111): warning CS0618: 'SKDropShadowImageFilterShadowMode' is obsolete: 'Use CreateDropShadow or CreateDropShadowOnly instead.'
> 11>C:\Projects\Microsoft.Maui.Graphics\src\Microsoft.Maui.Graphics.Skia\SkiaCanvasState.cs(360,20,360,136): warning CS0618: 'SKImageFilter.CreateDropShadow(float, float, float, float, SKColor, SKDropShadowImageFilterShadowMode, SKImageFilter, SKImageFilter.CropRect)' is obsolete: 'Use CreateDropShadow or CreateDropShadowOnly instead.'
> 11>C:\Projects\Microsoft.Maui.Graphics\src\Microsoft.Maui.Graphics.Skia\SkiaCanvas.cs(11,29,11,42): warning CS0414: The field 'SkiaCanvas._shaderMatrix' is assigned but its value is never used
> ```
> 
> * What will happen with platforms not supported in .NET MAUI (WPF etc)? Separate into Core/Community libraries or similar?

Answer myself https://github.com/dotnet/Microsoft.Maui.Graphics/issues/274

**Review by jonlipsky — APPROVED** [review]

**Pull request merged**
