### PR TITLE
Add Color Converter for String <-> Color

### PR DESCRIPTION
**Pull request by Redth**
This allows string <-> Color conversion for:

- HEX: #rgb, #argb, #rrggbb, #aarrggbb
- RGB: rgb(255,0,0), rgb(100%,0%,0%) - values in range 0-255 or 0%-100%
- RGBA: rgba(255, 0, 0, 0.8), rgba(100%, 0%, 0%, 0.8) - opacity is 0.0-1.0
- HSL: hsl(120, 100%, 50%) - h is 0-360, s and l are 0%-100%
- HSLA: hsla(120, 100%, 50%, .8) - opacity is 0.0-1.0
- HSV: hsv(120, 100%, 50%) - h is 0-360, s and v are 0%-100%
- HSVA: hsva(120, 100%, 50%, .8) - opacity is 0.0-1.0
- Predefined color - case insensitive

This also marks the Color type as compatible with this type converter.

- Adds a `Color.Parse(string)` method for parsing colors

### CODE REVIEW

**Review by mattleibow — APPROVED** [review]

**Comment by charlesroddie** [comment]
The need for Maui to have an optional XAML layer requires all libraries that MAUI depends on to add XAML-specific functionality?

The ugliness of supporting XAML, with non-generic reflection-heavy monstrosities in lieu of functions, makes this a large cost.

> This is helpful for XAML editor/hot reload/designer, though of course it's not coupled to XAML in any way, and can be useful in other scenarios where converting a string to Color is required.

If `public override object ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, object fromValue)` were replaced with `public Color? ColorFromString(string colorString)` then this statement would be correct and we would have a function usable in any scenario.

**Comment by Redth** [comment]
This was meant to be created as a draft so I've converted it to one.

This is simply a spike to see how helpful or not this is to have up-level as we're working on XAML editor/hot reload support which is now a bit different than Xamarin.Forms since the Color type and others are no longer in the same library as the MAUI XAML parts themselves.

My preference is also to avoid including this converter here, and it looks like it _should_ be possible to do without this PR, but there's a bit more work left to be sure of that.

**Comment by Redth** [comment]
Ok, looks like this is unnecessary and we can include the functionality we need in the designtools assembly.

**Review by Clancey — APPROVED** [review]

**Review by Clancey — APPROVED** [review]

**Comment by Redth** [comment]
We ended up having it be very advantageous to put the converter in this library from an engineering/maintenance cost perspective.

I stand by my originally statement that it is generally useful to have a type converter... After all, it's using System.ComponentModel.TypeConverter which you could do something like: `var color = (new ColorTypeConverter()).ConvertFromInvariantString("#000000");`, however I do agree @charlesroddie that it's more useful to have this available outside of the converter so I've added a .Parse(string) method to the Color type, and made the converter use that instead.

**Pull request merged**
